# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfdcd71c6262fc1d3d33573e688e8b2b7fbd9bd127a01eab373bc9395c54c9b26de7215c4681b0df9ef110a5d133e39b06434d21cc81392bceaa562e44c99843

test:
  secret_key_base: 826831803dbfb9ad83bfc2b545110c13feb937eadda331a5b87c9c11ad41db4b6b4b35358e725780bb3551543845586b3dcc8da110c18f65e34021b23789cc54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
